// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Invocation.proto
// Protobuf Java Version: 4.26.0

package com.lambda.hrpc.common.protocol;

public final class Invocation {
  private Invocation() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 0,
      /* suffix= */ "",
      Invocation.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AppInvocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lambda.hrpc.protocol.common.AppInvocation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string serviceName = 1;</code>
     * @return The serviceName.
     */
    java.lang.String getServiceName();
    /**
     * <code>string serviceName = 1;</code>
     * @return The bytes for serviceName.
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    /**
     * <code>string version = 2;</code>
     * @return The version.
     */
    java.lang.String getVersion();
    /**
     * <code>string version = 2;</code>
     * @return The bytes for version.
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>string methodName = 3;</code>
     * @return The methodName.
     */
    java.lang.String getMethodName();
    /**
     * <code>string methodName = 3;</code>
     * @return The bytes for methodName.
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>repeated string paramTypes = 4;</code>
     * @return A list containing the paramTypes.
     */
    java.util.List<java.lang.String>
        getParamTypesList();
    /**
     * <code>repeated string paramTypes = 4;</code>
     * @return The count of paramTypes.
     */
    int getParamTypesCount();
    /**
     * <code>repeated string paramTypes = 4;</code>
     * @param index The index of the element to return.
     * @return The paramTypes at the given index.
     */
    java.lang.String getParamTypes(int index);
    /**
     * <code>repeated string paramTypes = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the paramTypes at the given index.
     */
    com.google.protobuf.ByteString
        getParamTypesBytes(int index);

    /**
     * <code>repeated .google.protobuf.Any params = 5;</code>
     */
    java.util.List<com.google.protobuf.Any> 
        getParamsList();
    /**
     * <code>repeated .google.protobuf.Any params = 5;</code>
     */
    com.google.protobuf.Any getParams(int index);
    /**
     * <code>repeated .google.protobuf.Any params = 5;</code>
     */
    int getParamsCount();
    /**
     * <code>repeated .google.protobuf.Any params = 5;</code>
     */
    java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getParamsOrBuilderList();
    /**
     * <code>repeated .google.protobuf.Any params = 5;</code>
     */
    com.google.protobuf.AnyOrBuilder getParamsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.lambda.hrpc.protocol.common.AppInvocation}
   */
  public static final class AppInvocation extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.lambda.hrpc.protocol.common.AppInvocation)
      AppInvocationOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "",
        AppInvocation.class.getName());
    }
    // Use AppInvocation.newBuilder() to construct.
    private AppInvocation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AppInvocation() {
      serviceName_ = "";
      version_ = "";
      methodName_ = "";
      paramTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      params_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Invocation.internal_static_com_lambda_hrpc_protocol_common_AppInvocation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Invocation.internal_static_com_lambda_hrpc_protocol_common_AppInvocation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Invocation.AppInvocation.class, Invocation.AppInvocation.Builder.class);
    }

    public static final int SERVICENAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object serviceName_ = "";
    /**
     * <code>string serviceName = 1;</code>
     * @return The serviceName.
     */
    @java.lang.Override
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      }
    }
    /**
     * <code>string serviceName = 1;</code>
     * @return The bytes for serviceName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object version_ = "";
    /**
     * <code>string version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 2;</code>
     * @return The bytes for version.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHODNAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object methodName_ = "";
    /**
     * <code>string methodName = 3;</code>
     * @return The methodName.
     */
    @java.lang.Override
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <code>string methodName = 3;</code>
     * @return The bytes for methodName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMTYPES_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList paramTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string paramTypes = 4;</code>
     * @return A list containing the paramTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getParamTypesList() {
      return paramTypes_;
    }
    /**
     * <code>repeated string paramTypes = 4;</code>
     * @return The count of paramTypes.
     */
    public int getParamTypesCount() {
      return paramTypes_.size();
    }
    /**
     * <code>repeated string paramTypes = 4;</code>
     * @param index The index of the element to return.
     * @return The paramTypes at the given index.
     */
    public java.lang.String getParamTypes(int index) {
      return paramTypes_.get(index);
    }
    /**
     * <code>repeated string paramTypes = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the paramTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getParamTypesBytes(int index) {
      return paramTypes_.getByteString(index);
    }

    public static final int PARAMS_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private java.util.List<com.google.protobuf.Any> params_;
    /**
     * <code>repeated .google.protobuf.Any params = 5;</code>
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.Any> getParamsList() {
      return params_;
    }
    /**
     * <code>repeated .google.protobuf.Any params = 5;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getParamsOrBuilderList() {
      return params_;
    }
    /**
     * <code>repeated .google.protobuf.Any params = 5;</code>
     */
    @java.lang.Override
    public int getParamsCount() {
      return params_.size();
    }
    /**
     * <code>repeated .google.protobuf.Any params = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Any getParams(int index) {
      return params_.get(index);
    }
    /**
     * <code>repeated .google.protobuf.Any params = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getParamsOrBuilder(
        int index) {
      return params_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serviceName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, serviceName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, version_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(methodName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, methodName_);
      }
      for (int i = 0; i < paramTypes_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, paramTypes_.getRaw(i));
      }
      for (int i = 0; i < params_.size(); i++) {
        output.writeMessage(5, params_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serviceName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, serviceName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, version_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(methodName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, methodName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < paramTypes_.size(); i++) {
          dataSize += computeStringSizeNoTag(paramTypes_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getParamTypesList().size();
      }
      for (int i = 0; i < params_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, params_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Invocation.AppInvocation)) {
        return super.equals(obj);
      }
      Invocation.AppInvocation other = (Invocation.AppInvocation) obj;

      if (!getServiceName()
          .equals(other.getServiceName())) return false;
      if (!getVersion()
          .equals(other.getVersion())) return false;
      if (!getMethodName()
          .equals(other.getMethodName())) return false;
      if (!getParamTypesList()
          .equals(other.getParamTypesList())) return false;
      if (!getParamsList()
          .equals(other.getParamsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVICENAME_FIELD_NUMBER;
      hash = (53 * hash) + getServiceName().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      if (getParamTypesCount() > 0) {
        hash = (37 * hash) + PARAMTYPES_FIELD_NUMBER;
        hash = (53 * hash) + getParamTypesList().hashCode();
      }
      if (getParamsCount() > 0) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + getParamsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Invocation.AppInvocation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Invocation.AppInvocation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Invocation.AppInvocation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Invocation.AppInvocation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Invocation.AppInvocation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Invocation.AppInvocation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Invocation.AppInvocation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Invocation.AppInvocation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Invocation.AppInvocation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Invocation.AppInvocation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Invocation.AppInvocation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Invocation.AppInvocation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Invocation.AppInvocation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lambda.hrpc.protocol.common.AppInvocation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lambda.hrpc.protocol.common.AppInvocation)
        Invocation.AppInvocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Invocation.internal_static_com_lambda_hrpc_protocol_common_AppInvocation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Invocation.internal_static_com_lambda_hrpc_protocol_common_AppInvocation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Invocation.AppInvocation.class, Invocation.AppInvocation.Builder.class);
      }

      // Construct using com.lambda.hrpc.common.protocol.Invocation.AppInvocation.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        serviceName_ = "";
        version_ = "";
        methodName_ = "";
        paramTypes_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        if (paramsBuilder_ == null) {
          params_ = java.util.Collections.emptyList();
        } else {
          params_ = null;
          paramsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Invocation.internal_static_com_lambda_hrpc_protocol_common_AppInvocation_descriptor;
      }

      @java.lang.Override
      public Invocation.AppInvocation getDefaultInstanceForType() {
        return Invocation.AppInvocation.getDefaultInstance();
      }

      @java.lang.Override
      public Invocation.AppInvocation build() {
        Invocation.AppInvocation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Invocation.AppInvocation buildPartial() {
        Invocation.AppInvocation result = new Invocation.AppInvocation(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(Invocation.AppInvocation result) {
        if (paramsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0)) {
            params_ = java.util.Collections.unmodifiableList(params_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.params_ = params_;
        } else {
          result.params_ = paramsBuilder_.build();
        }
      }

      private void buildPartial0(Invocation.AppInvocation result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.serviceName_ = serviceName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.version_ = version_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.methodName_ = methodName_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          paramTypes_.makeImmutable();
          result.paramTypes_ = paramTypes_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Invocation.AppInvocation) {
          return mergeFrom((Invocation.AppInvocation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Invocation.AppInvocation other) {
        if (other == Invocation.AppInvocation.getDefaultInstance()) return this;
        if (!other.getServiceName().isEmpty()) {
          serviceName_ = other.serviceName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.paramTypes_.isEmpty()) {
          if (paramTypes_.isEmpty()) {
            paramTypes_ = other.paramTypes_;
            bitField0_ |= 0x00000008;
          } else {
            ensureParamTypesIsMutable();
            paramTypes_.addAll(other.paramTypes_);
          }
          onChanged();
        }
        if (paramsBuilder_ == null) {
          if (!other.params_.isEmpty()) {
            if (params_.isEmpty()) {
              params_ = other.params_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureParamsIsMutable();
              params_.addAll(other.params_);
            }
            onChanged();
          }
        } else {
          if (!other.params_.isEmpty()) {
            if (paramsBuilder_.isEmpty()) {
              paramsBuilder_.dispose();
              paramsBuilder_ = null;
              params_ = other.params_;
              bitField0_ = (bitField0_ & ~0x00000010);
              paramsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getParamsFieldBuilder() : null;
            } else {
              paramsBuilder_.addAllMessages(other.params_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                serviceName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                version_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                methodName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureParamTypesIsMutable();
                paramTypes_.add(s);
                break;
              } // case 34
              case 42: {
                com.google.protobuf.Any m =
                    input.readMessage(
                        com.google.protobuf.Any.parser(),
                        extensionRegistry);
                if (paramsBuilder_ == null) {
                  ensureParamsIsMutable();
                  params_.add(m);
                } else {
                  paramsBuilder_.addMessage(m);
                }
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object serviceName_ = "";
      /**
       * <code>string serviceName = 1;</code>
       * @return The serviceName.
       */
      public java.lang.String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string serviceName = 1;</code>
       * @return The bytes for serviceName.
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        java.lang.Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serviceName = 1;</code>
       * @param value The serviceName to set.
       * @return This builder for chaining.
       */
      public Builder setServiceName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        serviceName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string serviceName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServiceName() {
        serviceName_ = getDefaultInstance().getServiceName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string serviceName = 1;</code>
       * @param value The bytes for serviceName to set.
       * @return This builder for chaining.
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        serviceName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>string version = 2;</code>
       * @return The version.
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string version = 2;</code>
       * @return The bytes for version.
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 2;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        version_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        version_ = getDefaultInstance().getVersion();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string version = 2;</code>
       * @param value The bytes for version to set.
       * @return This builder for chaining.
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        version_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object methodName_ = "";
      /**
       * <code>string methodName = 3;</code>
       * @return The methodName.
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string methodName = 3;</code>
       * @return The bytes for methodName.
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string methodName = 3;</code>
       * @param value The methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        methodName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string methodName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethodName() {
        methodName_ = getDefaultInstance().getMethodName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string methodName = 3;</code>
       * @param value The bytes for methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        methodName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList paramTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureParamTypesIsMutable() {
        if (!paramTypes_.isModifiable()) {
          paramTypes_ = new com.google.protobuf.LazyStringArrayList(paramTypes_);
        }
        bitField0_ |= 0x00000008;
      }
      /**
       * <code>repeated string paramTypes = 4;</code>
       * @return A list containing the paramTypes.
       */
      public com.google.protobuf.ProtocolStringList
          getParamTypesList() {
        paramTypes_.makeImmutable();
        return paramTypes_;
      }
      /**
       * <code>repeated string paramTypes = 4;</code>
       * @return The count of paramTypes.
       */
      public int getParamTypesCount() {
        return paramTypes_.size();
      }
      /**
       * <code>repeated string paramTypes = 4;</code>
       * @param index The index of the element to return.
       * @return The paramTypes at the given index.
       */
      public java.lang.String getParamTypes(int index) {
        return paramTypes_.get(index);
      }
      /**
       * <code>repeated string paramTypes = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the paramTypes at the given index.
       */
      public com.google.protobuf.ByteString
          getParamTypesBytes(int index) {
        return paramTypes_.getByteString(index);
      }
      /**
       * <code>repeated string paramTypes = 4;</code>
       * @param index The index to set the value at.
       * @param value The paramTypes to set.
       * @return This builder for chaining.
       */
      public Builder setParamTypes(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParamTypesIsMutable();
        paramTypes_.set(index, value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paramTypes = 4;</code>
       * @param value The paramTypes to add.
       * @return This builder for chaining.
       */
      public Builder addParamTypes(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParamTypesIsMutable();
        paramTypes_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paramTypes = 4;</code>
       * @param values The paramTypes to add.
       * @return This builder for chaining.
       */
      public Builder addAllParamTypes(
          java.lang.Iterable<java.lang.String> values) {
        ensureParamTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, paramTypes_);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paramTypes = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearParamTypes() {
        paramTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paramTypes = 4;</code>
       * @param value The bytes of the paramTypes to add.
       * @return This builder for chaining.
       */
      public Builder addParamTypesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureParamTypesIsMutable();
        paramTypes_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.Any> params_ =
        java.util.Collections.emptyList();
      private void ensureParamsIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          params_ = new java.util.ArrayList<com.google.protobuf.Any>(params_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> paramsBuilder_;

      /**
       * <code>repeated .google.protobuf.Any params = 5;</code>
       */
      public java.util.List<com.google.protobuf.Any> getParamsList() {
        if (paramsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(params_);
        } else {
          return paramsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .google.protobuf.Any params = 5;</code>
       */
      public int getParamsCount() {
        if (paramsBuilder_ == null) {
          return params_.size();
        } else {
          return paramsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .google.protobuf.Any params = 5;</code>
       */
      public com.google.protobuf.Any getParams(int index) {
        if (paramsBuilder_ == null) {
          return params_.get(index);
        } else {
          return paramsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any params = 5;</code>
       */
      public Builder setParams(
          int index, com.google.protobuf.Any value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamsIsMutable();
          params_.set(index, value);
          onChanged();
        } else {
          paramsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any params = 5;</code>
       */
      public Builder setParams(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.set(index, builderForValue.build());
          onChanged();
        } else {
          paramsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any params = 5;</code>
       */
      public Builder addParams(com.google.protobuf.Any value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamsIsMutable();
          params_.add(value);
          onChanged();
        } else {
          paramsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any params = 5;</code>
       */
      public Builder addParams(
          int index, com.google.protobuf.Any value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamsIsMutable();
          params_.add(index, value);
          onChanged();
        } else {
          paramsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any params = 5;</code>
       */
      public Builder addParams(
          com.google.protobuf.Any.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.add(builderForValue.build());
          onChanged();
        } else {
          paramsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any params = 5;</code>
       */
      public Builder addParams(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.add(index, builderForValue.build());
          onChanged();
        } else {
          paramsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any params = 5;</code>
       */
      public Builder addAllParams(
          java.lang.Iterable<? extends com.google.protobuf.Any> values) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, params_);
          onChanged();
        } else {
          paramsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any params = 5;</code>
       */
      public Builder clearParams() {
        if (paramsBuilder_ == null) {
          params_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          paramsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any params = 5;</code>
       */
      public Builder removeParams(int index) {
        if (paramsBuilder_ == null) {
          ensureParamsIsMutable();
          params_.remove(index);
          onChanged();
        } else {
          paramsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any params = 5;</code>
       */
      public com.google.protobuf.Any.Builder getParamsBuilder(
          int index) {
        return getParamsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .google.protobuf.Any params = 5;</code>
       */
      public com.google.protobuf.AnyOrBuilder getParamsOrBuilder(
          int index) {
        if (paramsBuilder_ == null) {
          return params_.get(index);  } else {
          return paramsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any params = 5;</code>
       */
      public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
           getParamsOrBuilderList() {
        if (paramsBuilder_ != null) {
          return paramsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(params_);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any params = 5;</code>
       */
      public com.google.protobuf.Any.Builder addParamsBuilder() {
        return getParamsFieldBuilder().addBuilder(
            com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Any params = 5;</code>
       */
      public com.google.protobuf.Any.Builder addParamsBuilder(
          int index) {
        return getParamsFieldBuilder().addBuilder(
            index, com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Any params = 5;</code>
       */
      public java.util.List<com.google.protobuf.Any.Builder> 
           getParamsBuilderList() {
        return getParamsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getParamsFieldBuilder() {
        if (paramsBuilder_ == null) {
          paramsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  params_,
                  ((bitField0_ & 0x00000010) != 0),
                  getParentForChildren(),
                  isClean());
          params_ = null;
        }
        return paramsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.lambda.hrpc.protocol.common.AppInvocation)
    }

    // @@protoc_insertion_point(class_scope:com.lambda.hrpc.protocol.common.AppInvocation)
    private static final Invocation.AppInvocation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Invocation.AppInvocation();
    }

    public static Invocation.AppInvocation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppInvocation>
        PARSER = new com.google.protobuf.AbstractParser<AppInvocation>() {
      @java.lang.Override
      public AppInvocation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AppInvocation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppInvocation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Invocation.AppInvocation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lambda_hrpc_protocol_common_AppInvocation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_lambda_hrpc_protocol_common_AppInvocation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Invocation.proto\022\037com.lambda.hrpc.prot" +
      "ocol.common\032\031google/protobuf/any.proto\"\203" +
      "\001\n\rAppInvocation\022\023\n\013serviceName\030\001 \001(\t\022\017\n" +
      "\007version\030\002 \001(\t\022\022\n\nmethodName\030\003 \001(\t\022\022\n\npa" +
      "ramTypes\030\004 \003(\t\022$\n\006params\030\005 \003(\0132\024.google." +
      "protobuf.Anyb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_com_lambda_hrpc_protocol_common_AppInvocation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lambda_hrpc_protocol_common_AppInvocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_lambda_hrpc_protocol_common_AppInvocation_descriptor,
        new java.lang.String[] { "ServiceName", "Version", "MethodName", "ParamTypes", "Params", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
